name: Deploy to Vercel

on:
  push:
    branches: [ main ]
  workflow_dispatch: # Allow manual deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: |
          package-lock.json
          apps/web/package-lock.json
          packages/*/package-lock.json
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build application
      run: npm run build
    
    - name: Deploy to Vercel
      uses: amondnet/vercel-action@v25
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
        working-directory: ./apps/web
        vercel-args: '--prod'
    
    - name: Comment deployment status
      uses: actions/github-script@v7
      with:
        script: |
          const { data: deployment } = await github.rest.repos.listDeployments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: context.ref,
            per_page: 1
          });
          
          if (deployment.length > 0) {
            github.rest.issues.createComment({
              issue_number: context.issue?.number || 0,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🚀 Deployment successful! Application deployed to Vercel.\n\nCommit: ${context.sha}\nBranch: ${context.ref}`
            });
          }
